In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_excel("Telco_customer_churn.xlsx")

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

In [18]:

df[df['Churn Value'] == 1]['Tenure Months'].mean()

np.float64(17.979133226324237)

In [19]:
df[df['Churn Value'] == 0]['Tenure Months'].mean()

np.float64(37.56996521066873)

In [25]:
new_df = df[df['Tenure Months'] < 20]
new_df.groupby("Churn Value").agg({"Churn Value": ["count", "mean", "median"]})

            Churn Value
                  count mean median
Churn Value
0                  1574  0.0    0.0
1                  1233  1.0    1.0

In [27]:
df.head ()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [29]:
df['Contract'].unique().tolist()

['Month-to-month', 'Two year', 'One year']

In [36]:
df.groupby(["Contract", "Churn Value"]).agg({"Churn Value": ["count", "mean", "median"]})

                          Churn Value
                                count mean median
Tenure Months Churn Value
0             0                    11  0.0    0.0
1             0                   233  0.0    0.0
              1                   380  1.0    1.0
2             0                   115  0.0    0.0
              1                   123  1.0    1.0
...                               ...  ...    ...
70            1                    11  1.0    1.0
71            0                   164  0.0    0.0
              1                     6  1.0    1.0
72            0                   356  0.0    0.0
              1                     6  1.0    1.0

[145 rows x 3 columns]

In [34]:
grouped = df.groupby(["Contract", "Churn Value"]).size().reset_index(name="count")

# total per Contract
grouped["total"] = grouped.groupby("Contract")["count"].transform("sum")

# percentage
grouped["percentage"] = (grouped["count"] / grouped["total"]) * 100

grouped

         Contract  Churn Value  count  total  percentage
0  Month-to-month            0   2220   3875   57.290323
1  Month-to-month            1   1655   3875   42.709677
2        One year            0   1307   1473   88.730482
3        One year            1    166   1473   11.269518
4        Two year            0   1647   1695   97.168142
5        Two year            1     48   1695    2.831858

In [40]:
df['tenure_bin'] = pd.cut(df['Tenure Months'], bins=[0, 12, 24, 48, 72])
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason,tenure_bin
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer,"(0, 12]"
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved,"(0, 12]"
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved,"(0, 12]"
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved,"(24, 48]"
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices,"(48, 72]"

In [43]:
df = df[df['Contract'] == 	"Month-to-month"]
grouped = df.groupby(["Contract", "tenure_bin", "Churn Value"]).size().reset_index(name="count")

# total per Contract
grouped["total"] = grouped.groupby("tenure_bin")["count"].transform("sum")

# percentage
grouped["percentage"] = (grouped["count"] / grouped["total"]) * 100

grouped

/tmp/ipykernel_6129/819978264.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby(["Contract", "tenure_bin", "Churn Value"]).size().reset_index(name="count")
/tmp/ipykernel_6129/819978264.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped["total"] = grouped.groupby("tenure_bin")["count"].transform("sum")

         Contract tenure_bin  Churn Value  count  total  percentage
0  Month-to-month    (0, 12]            0    970   1994   48.645938
1  Month-to-month    (0, 12]            1   1024   1994   51.354062
2  Month-to-month   (12, 24]            0    459    737   62.279512
3  Month-to-month   (12, 24]            1    278    737   37.720488
4  Month-to-month   (24, 48]            0    538    802   67.082294
5  Month-to-month   (24, 48]            1    264    802   32.917706
6  Month-to-month   (48, 72]            0    253    342   73.976608
7  Month-to-month   (48, 72]            1     89    342   26.023392